### PR TITLE
Update to use godotenv

### PR DESCRIPTION
**Pull request by jimmychu0807**
@AstaFrode I have closed #70 and refer to this PR instead.

The README.md is also improved. I updated the title capitalisation according to [**Capitalize My Title**](https://capitalizemytitle.com/) website.

**Question**:

1. How do you prepare a boot peer for P2P? I realize a newly-started local node cannot be served as a boot peer. It will return an error when connecting to it.

### CODE REVIEW

**Comment by AstaFrode** [comment]
@jimmychu0807 The bootstrap node can only be run by ourselves, one has already been run: _dnsaddr.bootstrap-kldr.cess.cloud

**Comment by jimmychu0807** [comment]
I see. Is it possible to run a local node, but connecting to the provided boot peer: `_dnsaddr.bootstrap-kldr.cess.cloud`? Currently it will return an error.

**Comment by AstaFrode** [comment]
There are now 3 services running under this domain again, which may later be run on separate servers to avoid all services going down at the same time.

**Comment by AstaFrode** [comment]
@jimmychu0807 There are now 3 services running under this domain, which may later be run on separate servers to avoid all services going down at the same time.

**Pull request merged**
